### ISSUE TITLE
KMC fails but Hypo still runs

### ISSUE THREAD

**Issue by nadegeguiglielmoni** [kensung-lab/hypo#3]
Hello,

Thank you for this tool.

I have tried Hypo on Nanopore long read assemblies and got a satisfying improvement in the quality of my assemblies.

However, I have noticed that when I run it, I get an error message saying that KMC failed to run:

``[Hypo::Utils] Info: Value of K chosen for the given genome size (200m): 15
[Hypo::Utils] Info: File size expected for the given genome size (200m) and cov (70): 28G
Given Command: hypo  -r illuminaPE_170.fa -d raven_default.fasta -b chis2.raven_default.illumina_PE170.sam -c 70 -s 200m -o chis2.raven_hypo.illumina_PE170.fasta -t 6.
[Hypo::Utils] Info: Intermediate Files will NOT be stored.
[Hypo::Utils] Info: Beginning from stage: 0
[SolidKmers] Error: Failed running KMC.
RESOURCES ([Hypo:Hypo]: Computed Solid kmers. ): TIME= 0.0484691 sec; PEAK RSS (so far)= 150MB; CURRENT RSS (so far)= 150MB.
[Hypo::Hypo] Info: Number of (canonical) solid kmers (nonhp) : 0
RESOURCES ([Hypo:Hypo]: Loaded Contigs. ): TIME= 0.429875 sec; PEAK RSS (so far)= 305MB; CURRENT RSS (so far)= 305MB.
RESOURCES ([Hypo:Hypo]: Found Solid pos in contigs. ): TIME= 0.784538 sec; PEAK RSS (so far)= 311MB; CURRENT RSS (so far)= 311MB.
``

What confuses me is that my assembly is still polished. Does it mean that Hypo can work around Hypo if it fails? Or that I do not get the optimal Hypo run?  
I have installed KMC (not using conda though) and added it to my path.

**Comment by Ritu-Kundu** [comment]
Hi,

Thanks for using our polisher. It is a bug that we are proceeding even if KMC fails to run. We will correct it and push the updated version in a couple of days. But it makes sense that the draft will still be polished because KMC output is being used to compute the regions in draft we call "Strong Regions (SR)" (which do not get polished using POA). No KMC output simply means the whole contig will be polished (albeit a bit slower than what should have been its speed with  SR). 

Regarding the failure to run KMC, could you please provide us with the following information?
1. KMC version
2. Contents of the "aux" folder in the working directory where hypo was running.

Also, would it be possible for you to share the files (especially the reads file) with us?

**Comment by Ritu-Kundu** [comment]
Hi,

Assuming your read-file is in multi-fasta format, the issue may be because KMC uses different flag for multi-fasta which we had not used in the module SUK. We have corrected the bug. Could you please try again with the updated version.

By the way, we have also made the conda package available for easy installation.

**Comment by nadegeguiglielmoni** [comment]
Hello, 
I tried the updated version and I no longer get the error message, thank you.
I will try the conda installation on a cluster, on which I had not been able to install hypo yet.
